name: Compiling
run-name: Compiling of .tex
on:
  push:
    branches:
      - main
jobs:
#  downloading:
#    runs-on: ubuntu-latest
#    steps:
#      - run: sudo apt-get install texlive-latex-base
#      - run: sudo apt-get install texlive-fonts-recommended
#      - run: sudo apt-get install texlive-fonts-extra
#      - run: sudo apt-get install texlive-latex-extra
  compiling:
    runs-on: ubuntu-latest
    steps:
    - name: Check directory
      run: |
        echo "${GITHUB_WORKSPACE}"
        
    - name: cd
      run: cd "${GITHUB_WORKSPACE}"
      
    - name: listing
      run: ls
      
    - name: make
      run: make -f Makefile
