name: Compiling
run-name: Compiling of .tex
on:
  push:
    branches:
      - main
jobs:
#  downloading:
#    runs-on: ubuntu-latest
#    steps:
#      - run: sudo apt-get install texlive-latex-base
#      - run: sudo apt-get install texlive-fonts-recommended
#      - run: sudo apt-get install texlive-fonts-extra
#      - run: sudo apt-get install texlive-latex-extra
  compiling:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Directory
        run: |
          sudo apt-get install texlive-latex-base
          sudo apt-get install texlive-fonts-recommended
          sudo apt-get install texlive-fonts-extra
          sudo apt-get install texlive-latex-extra
          make -f Makefile
