name: Compiling
run-name: Compiling of .tex
on:
  push:
    branches:
      - main
jobs:
#  downloading:
#    runs-on: ubuntu-latest
#    steps:
#      - run: sudo apt-get install texlive-latex-base
#      - run: sudo apt-get install texlive-fonts-recommended
#      - run: sudo apt-get install texlive-fonts-extra
#      - run: sudo apt-get install texlive-latex-extra
  compiling:
    runs-on: ubuntu-latest
    steps:
    - name: Check directory
      run: |
        echo "repository variable : ${{ vars.REPOSITORY_VAR }}"
        echo "organization variable : ${{ vars.ORGANIZATION_VAR }}"
        echo "overridden variable : ${{ vars.OVERRIDE_VAR }}"
        echo "variable from shell environment : $env_var"
        
    - name: cd
      run: cd "${{ vars.GITHUB_ACTION_PATH }}"
      
    - name: make
      run: make -f Makefile
