name: Compiling
run-name: Compiling of .tex
on:
  push:
    branches:
      - main
jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install texlive-latex-base
      - run: sudo apt-get install texlive-fonts-recommended
      - run: sudo apt-get install texlive-fonts-extra
      - run: sudo apt-get install texlive-latex-extra
      - run: make -f Makefile
