name: Compiling
run-name: Compiling of .tex
on:
  push:
    branches:
      - main
jobs:
  compiling:
    runs-on: ubuntu-latest
    steps:
      - run: cd Q4_EPL
      - run: ls
      - run: make full
